// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMedical = "tblMedical"

// Medical mapped from table <tblMedical>
type Medical struct {
	ID                int64   `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`              // 自增主键
	Height            float32 `gorm:"column:height;type:float unsigned;not null" json:"height"`                         // 身高，单位：厘米
	Weight            float32 `gorm:"column:weight;type:float unsigned;not null" json:"weight"`                         // 体重，单位：公斤
	HeadCircumference float32 `gorm:"column:head_circumference;type:float unsigned;not null" json:"head_circumference"` // 头围
	OperatorID        int64   `gorm:"column:operator_id;type:int;not null" json:"operator_id"`                          // 操作人id
	CreatedAt         int64   `gorm:"column:created_at;type:int;not null" json:"created_at"`                            // 创建时间
	UpdatedAt         int64   `gorm:"column:updated_at;type:int;not null" json:"updated_at"`                            // 更新时间
	DeletedAt         int64   `gorm:"column:deleted_at;type:int;not null" json:"deleted_at"`                            // 删除时间
}

// TableName Medical's table name
func (*Medical) TableName() string {
	return TableNameMedical
}
