// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUser = "tblUser"

// User mapped from table <tblUser>
type User struct {
	ID        int64  `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`                 // 自增主键
	Email     string `gorm:"column:email;type:varchar(50);not null;uniqueIndex:uk_email,priority:1" json:"email"` // 电子邮箱
	Password  string `gorm:"column:password;type:varchar(20);not null" json:"password"`                           // 密码
	CreatedAt int64  `gorm:"column:created_at;type:int;not null" json:"created_at"`                               // 创建时间
	UpdatedAt int64  `gorm:"1111" json:"updated_at"`                                                              // 更新时间
	DeletedAt int64  `gorm:"column:deleted_at;type:int;not null" json:"deleted_at"`                               // 删除时间
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
